[package]
name = "trousers"
version = "0.1.0"
authors = ["Richard Wang <zhwang@live.com.au>"]
description = "TrouSerS bindings for Rust"
repository = "https://github.com/rzhw/rust-trousers"
keywords = ["TrouSerS", "TPM", "TSS"]
license = "MIT"

[lib]
name = "trousers"
path = "src/lib.rs"
